name: On Push GH Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkhout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
#      - name: Build with Maven
#        run: mvn --batch-mode --update-snapshots verify
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - run: mvn test
      - run: mvn clean package
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag phenomenonxxi/gt-out-app
      - name: Docker Push
        run: docker push phenomenonxxi/gt-out-app
      - name: Docker Pull, Build and Run
        run: docker pull phenomenonxxi/gt-out-app:latest
      - run: docker run phenomenonxxi/gt-out-app:latest
